/*
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package voucherify.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import voucherify.client.model.EarningRuleBaseLoyaltyOrderItemsQuantity;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import voucherify.client.JSON;

/**
 * EarningRuleBaseLoyaltyOrderItems
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")

public class EarningRuleBaseLoyaltyOrderItems {
  public static final String SERIALIZED_NAME_QUANTITY = "quantity";
  @SerializedName(SERIALIZED_NAME_QUANTITY)
  private EarningRuleBaseLoyaltyOrderItemsQuantity quantity;

  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  private EarningRuleBaseLoyaltyOrderItemsQuantity amount;

  public static final String SERIALIZED_NAME_SUBTOTAL_AMOUNT = "subtotal_amount";
  @SerializedName(SERIALIZED_NAME_SUBTOTAL_AMOUNT)
  private EarningRuleBaseLoyaltyOrderItemsQuantity subtotalAmount;

  public EarningRuleBaseLoyaltyOrderItems() {
  }

  public EarningRuleBaseLoyaltyOrderItems quantity(EarningRuleBaseLoyaltyOrderItemsQuantity quantity) {
    
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @javax.annotation.Nullable
  public EarningRuleBaseLoyaltyOrderItemsQuantity getQuantity() {
    return quantity;
  }


  public void setQuantity(EarningRuleBaseLoyaltyOrderItemsQuantity quantity) {
    this.quantity = quantity;
  }


  public EarningRuleBaseLoyaltyOrderItems amount(EarningRuleBaseLoyaltyOrderItemsQuantity amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @javax.annotation.Nullable
  public EarningRuleBaseLoyaltyOrderItemsQuantity getAmount() {
    return amount;
  }


  public void setAmount(EarningRuleBaseLoyaltyOrderItemsQuantity amount) {
    this.amount = amount;
  }


  public EarningRuleBaseLoyaltyOrderItems subtotalAmount(EarningRuleBaseLoyaltyOrderItemsQuantity subtotalAmount) {
    
    this.subtotalAmount = subtotalAmount;
    return this;
  }

   /**
   * Get subtotalAmount
   * @return subtotalAmount
  **/
  @javax.annotation.Nullable
  public EarningRuleBaseLoyaltyOrderItemsQuantity getSubtotalAmount() {
    return subtotalAmount;
  }


  public void setSubtotalAmount(EarningRuleBaseLoyaltyOrderItemsQuantity subtotalAmount) {
    this.subtotalAmount = subtotalAmount;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EarningRuleBaseLoyaltyOrderItems earningRuleBaseLoyaltyOrderItems = (EarningRuleBaseLoyaltyOrderItems) o;
    return Objects.equals(this.quantity, earningRuleBaseLoyaltyOrderItems.quantity) &&
        Objects.equals(this.amount, earningRuleBaseLoyaltyOrderItems.amount) &&
        Objects.equals(this.subtotalAmount, earningRuleBaseLoyaltyOrderItems.subtotalAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quantity, amount, subtotalAmount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EarningRuleBaseLoyaltyOrderItems {\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    subtotalAmount: ").append(toIndentedString(subtotalAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("quantity");
    openapiFields.add("amount");
    openapiFields.add("subtotal_amount");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to EarningRuleBaseLoyaltyOrderItems
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EarningRuleBaseLoyaltyOrderItems.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EarningRuleBaseLoyaltyOrderItems is not found in the empty JSON string", EarningRuleBaseLoyaltyOrderItems.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EarningRuleBaseLoyaltyOrderItems.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EarningRuleBaseLoyaltyOrderItems` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `quantity`
      if (jsonObj.get("quantity") != null && !jsonObj.get("quantity").isJsonNull()) {
        EarningRuleBaseLoyaltyOrderItemsQuantity.validateJsonElement(jsonObj.get("quantity"));
      }
      // validate the optional field `amount`
      if (jsonObj.get("amount") != null && !jsonObj.get("amount").isJsonNull()) {
        EarningRuleBaseLoyaltyOrderItemsQuantity.validateJsonElement(jsonObj.get("amount"));
      }
      // validate the optional field `subtotal_amount`
      if (jsonObj.get("subtotal_amount") != null && !jsonObj.get("subtotal_amount").isJsonNull()) {
        EarningRuleBaseLoyaltyOrderItemsQuantity.validateJsonElement(jsonObj.get("subtotal_amount"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EarningRuleBaseLoyaltyOrderItems.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EarningRuleBaseLoyaltyOrderItems' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EarningRuleBaseLoyaltyOrderItems> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EarningRuleBaseLoyaltyOrderItems.class));

       return (TypeAdapter<T>) new TypeAdapter<EarningRuleBaseLoyaltyOrderItems>() {
           @Override
           public void write(JsonWriter out, EarningRuleBaseLoyaltyOrderItems value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EarningRuleBaseLoyaltyOrderItems read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of EarningRuleBaseLoyaltyOrderItems given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of EarningRuleBaseLoyaltyOrderItems
  * @throws IOException if the JSON string is invalid with respect to EarningRuleBaseLoyaltyOrderItems
  */
  public static EarningRuleBaseLoyaltyOrderItems fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EarningRuleBaseLoyaltyOrderItems.class);
  }

 /**
  * Convert an instance of EarningRuleBaseLoyaltyOrderItems to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

