/*
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package voucherify.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import voucherify.client.model.Address1;
import voucherify.client.model.Brand1;
import voucherify.client.model.Cockpit1;
import voucherify.client.model.Contact1;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import voucherify.client.JSON;

/**
 * Request body schema for **POST** &#x60;/management/v1/projects/{projectId}/branding&#x60;.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")

public class ManagementProjectsBrandingCreateRequestBody {
  public static final String SERIALIZED_NAME_BRAND = "brand";
  @SerializedName(SERIALIZED_NAME_BRAND)
  private Brand1 brand;

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private Address1 address;

  public static final String SERIALIZED_NAME_CONTACT = "contact";
  @SerializedName(SERIALIZED_NAME_CONTACT)
  private Contact1 contact;

  public static final String SERIALIZED_NAME_COCKPITS = "cockpits";
  @SerializedName(SERIALIZED_NAME_COCKPITS)
  private Cockpit1 cockpits;

  public ManagementProjectsBrandingCreateRequestBody() {
  }

  public ManagementProjectsBrandingCreateRequestBody brand(Brand1 brand) {
    
    this.brand = brand;
    return this;
  }

   /**
   * Get brand
   * @return brand
  **/
  @javax.annotation.Nonnull
  public Brand1 getBrand() {
    return brand;
  }


  public void setBrand(Brand1 brand) {
    this.brand = brand;
  }


  public ManagementProjectsBrandingCreateRequestBody address(Address1 address) {
    
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @javax.annotation.Nonnull
  public Address1 getAddress() {
    return address;
  }


  public void setAddress(Address1 address) {
    this.address = address;
  }


  public ManagementProjectsBrandingCreateRequestBody contact(Contact1 contact) {
    
    this.contact = contact;
    return this;
  }

   /**
   * Get contact
   * @return contact
  **/
  @javax.annotation.Nonnull
  public Contact1 getContact() {
    return contact;
  }


  public void setContact(Contact1 contact) {
    this.contact = contact;
  }


  public ManagementProjectsBrandingCreateRequestBody cockpits(Cockpit1 cockpits) {
    
    this.cockpits = cockpits;
    return this;
  }

   /**
   * Get cockpits
   * @return cockpits
  **/
  @javax.annotation.Nullable
  public Cockpit1 getCockpits() {
    return cockpits;
  }


  public void setCockpits(Cockpit1 cockpits) {
    this.cockpits = cockpits;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ManagementProjectsBrandingCreateRequestBody managementProjectsBrandingCreateRequestBody = (ManagementProjectsBrandingCreateRequestBody) o;
    return Objects.equals(this.brand, managementProjectsBrandingCreateRequestBody.brand) &&
        Objects.equals(this.address, managementProjectsBrandingCreateRequestBody.address) &&
        Objects.equals(this.contact, managementProjectsBrandingCreateRequestBody.contact) &&
        Objects.equals(this.cockpits, managementProjectsBrandingCreateRequestBody.cockpits);
  }

  @Override
  public int hashCode() {
    return Objects.hash(brand, address, contact, cockpits);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ManagementProjectsBrandingCreateRequestBody {\n");
    sb.append("    brand: ").append(toIndentedString(brand)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    contact: ").append(toIndentedString(contact)).append("\n");
    sb.append("    cockpits: ").append(toIndentedString(cockpits)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("brand");
    openapiFields.add("address");
    openapiFields.add("contact");
    openapiFields.add("cockpits");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("brand");
    openapiRequiredFields.add("address");
    openapiRequiredFields.add("contact");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ManagementProjectsBrandingCreateRequestBody
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ManagementProjectsBrandingCreateRequestBody.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ManagementProjectsBrandingCreateRequestBody is not found in the empty JSON string", ManagementProjectsBrandingCreateRequestBody.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ManagementProjectsBrandingCreateRequestBody.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ManagementProjectsBrandingCreateRequestBody` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ManagementProjectsBrandingCreateRequestBody.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `brand`
      Brand1.validateJsonElement(jsonObj.get("brand"));
      // validate the required field `address`
      Address1.validateJsonElement(jsonObj.get("address"));
      // validate the required field `contact`
      Contact1.validateJsonElement(jsonObj.get("contact"));
      // validate the optional field `cockpits`
      if (jsonObj.get("cockpits") != null && !jsonObj.get("cockpits").isJsonNull()) {
        Cockpit1.validateJsonElement(jsonObj.get("cockpits"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ManagementProjectsBrandingCreateRequestBody.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ManagementProjectsBrandingCreateRequestBody' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ManagementProjectsBrandingCreateRequestBody> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ManagementProjectsBrandingCreateRequestBody.class));

       return (TypeAdapter<T>) new TypeAdapter<ManagementProjectsBrandingCreateRequestBody>() {
           @Override
           public void write(JsonWriter out, ManagementProjectsBrandingCreateRequestBody value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ManagementProjectsBrandingCreateRequestBody read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ManagementProjectsBrandingCreateRequestBody given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ManagementProjectsBrandingCreateRequestBody
  * @throws IOException if the JSON string is invalid with respect to ManagementProjectsBrandingCreateRequestBody
  */
  public static ManagementProjectsBrandingCreateRequestBody fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ManagementProjectsBrandingCreateRequestBody.class);
  }

 /**
  * Convert an instance of ManagementProjectsBrandingCreateRequestBody to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

