/*
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package voucherify.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import voucherify.client.model.RedemptionsListResponseBodyRedemptionsItemPromotionTierSummaryOrders;
import voucherify.client.model.RedemptionsListResponseBodyRedemptionsItemPromotionTierSummaryRedemptions;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import voucherify.client.JSON;

/**
 * RedemptionsListResponseBodyRedemptionsItemPromotionTierSummary
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")

public class RedemptionsListResponseBodyRedemptionsItemPromotionTierSummary {
  public static final String SERIALIZED_NAME_REDEMPTIONS = "redemptions";
  @SerializedName(SERIALIZED_NAME_REDEMPTIONS)
  private RedemptionsListResponseBodyRedemptionsItemPromotionTierSummaryRedemptions redemptions;

  public static final String SERIALIZED_NAME_ORDERS = "orders";
  @SerializedName(SERIALIZED_NAME_ORDERS)
  private RedemptionsListResponseBodyRedemptionsItemPromotionTierSummaryOrders orders;

  public RedemptionsListResponseBodyRedemptionsItemPromotionTierSummary() {
  }

  public RedemptionsListResponseBodyRedemptionsItemPromotionTierSummary redemptions(RedemptionsListResponseBodyRedemptionsItemPromotionTierSummaryRedemptions redemptions) {
    
    this.redemptions = redemptions;
    return this;
  }

   /**
   * Get redemptions
   * @return redemptions
  **/
  @javax.annotation.Nullable
  public RedemptionsListResponseBodyRedemptionsItemPromotionTierSummaryRedemptions getRedemptions() {
    return redemptions;
  }


  public void setRedemptions(RedemptionsListResponseBodyRedemptionsItemPromotionTierSummaryRedemptions redemptions) {
    this.redemptions = redemptions;
  }


  public RedemptionsListResponseBodyRedemptionsItemPromotionTierSummary orders(RedemptionsListResponseBodyRedemptionsItemPromotionTierSummaryOrders orders) {
    
    this.orders = orders;
    return this;
  }

   /**
   * Get orders
   * @return orders
  **/
  @javax.annotation.Nullable
  public RedemptionsListResponseBodyRedemptionsItemPromotionTierSummaryOrders getOrders() {
    return orders;
  }


  public void setOrders(RedemptionsListResponseBodyRedemptionsItemPromotionTierSummaryOrders orders) {
    this.orders = orders;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RedemptionsListResponseBodyRedemptionsItemPromotionTierSummary redemptionsListResponseBodyRedemptionsItemPromotionTierSummary = (RedemptionsListResponseBodyRedemptionsItemPromotionTierSummary) o;
    return Objects.equals(this.redemptions, redemptionsListResponseBodyRedemptionsItemPromotionTierSummary.redemptions) &&
        Objects.equals(this.orders, redemptionsListResponseBodyRedemptionsItemPromotionTierSummary.orders);
  }

  @Override
  public int hashCode() {
    return Objects.hash(redemptions, orders);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RedemptionsListResponseBodyRedemptionsItemPromotionTierSummary {\n");
    sb.append("    redemptions: ").append(toIndentedString(redemptions)).append("\n");
    sb.append("    orders: ").append(toIndentedString(orders)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("redemptions");
    openapiFields.add("orders");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to RedemptionsListResponseBodyRedemptionsItemPromotionTierSummary
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RedemptionsListResponseBodyRedemptionsItemPromotionTierSummary.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RedemptionsListResponseBodyRedemptionsItemPromotionTierSummary is not found in the empty JSON string", RedemptionsListResponseBodyRedemptionsItemPromotionTierSummary.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RedemptionsListResponseBodyRedemptionsItemPromotionTierSummary.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RedemptionsListResponseBodyRedemptionsItemPromotionTierSummary` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `redemptions`
      if (jsonObj.get("redemptions") != null && !jsonObj.get("redemptions").isJsonNull()) {
        RedemptionsListResponseBodyRedemptionsItemPromotionTierSummaryRedemptions.validateJsonElement(jsonObj.get("redemptions"));
      }
      // validate the optional field `orders`
      if (jsonObj.get("orders") != null && !jsonObj.get("orders").isJsonNull()) {
        RedemptionsListResponseBodyRedemptionsItemPromotionTierSummaryOrders.validateJsonElement(jsonObj.get("orders"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RedemptionsListResponseBodyRedemptionsItemPromotionTierSummary.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RedemptionsListResponseBodyRedemptionsItemPromotionTierSummary' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RedemptionsListResponseBodyRedemptionsItemPromotionTierSummary> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RedemptionsListResponseBodyRedemptionsItemPromotionTierSummary.class));

       return (TypeAdapter<T>) new TypeAdapter<RedemptionsListResponseBodyRedemptionsItemPromotionTierSummary>() {
           @Override
           public void write(JsonWriter out, RedemptionsListResponseBodyRedemptionsItemPromotionTierSummary value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RedemptionsListResponseBodyRedemptionsItemPromotionTierSummary read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of RedemptionsListResponseBodyRedemptionsItemPromotionTierSummary given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of RedemptionsListResponseBodyRedemptionsItemPromotionTierSummary
  * @throws IOException if the JSON string is invalid with respect to RedemptionsListResponseBodyRedemptionsItemPromotionTierSummary
  */
  public static RedemptionsListResponseBodyRedemptionsItemPromotionTierSummary fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RedemptionsListResponseBodyRedemptionsItemPromotionTierSummary.class);
  }

 /**
  * Convert an instance of RedemptionsListResponseBodyRedemptionsItemPromotionTierSummary to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

