/*
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package voucherify.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import voucherify.client.model.ApplicableTo;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import voucherify.client.JSON;

/**
 * ValidationRuleBaseApplicableTo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")

public class ValidationRuleBaseApplicableTo {
  public static final String SERIALIZED_NAME_EXCLUDED = "excluded";
  @SerializedName(SERIALIZED_NAME_EXCLUDED)
  private List<ApplicableTo> excluded;

  public static final String SERIALIZED_NAME_INCLUDED = "included";
  @SerializedName(SERIALIZED_NAME_INCLUDED)
  private List<ApplicableTo> included;

  public static final String SERIALIZED_NAME_INCLUDED_ALL = "included_all";
  @SerializedName(SERIALIZED_NAME_INCLUDED_ALL)
  private Boolean includedAll;

  public ValidationRuleBaseApplicableTo() {
  }

  public ValidationRuleBaseApplicableTo excluded(List<ApplicableTo> excluded) {
    
    this.excluded = excluded;
    return this;
  }

  public ValidationRuleBaseApplicableTo addExcludedItem(ApplicableTo excludedItem) {
    if (this.excluded == null) {
      this.excluded = new ArrayList<>();
    }
    this.excluded.add(excludedItem);
    return this;
  }

   /**
   * Defines which items are excluded from a discount.
   * @return excluded
  **/
  @javax.annotation.Nullable
  public List<ApplicableTo> getExcluded() {
    return excluded;
  }


  public void setExcluded(List<ApplicableTo> excluded) {
    this.excluded = excluded;
  }


  public ValidationRuleBaseApplicableTo included(List<ApplicableTo> included) {
    
    this.included = included;
    return this;
  }

  public ValidationRuleBaseApplicableTo addIncludedItem(ApplicableTo includedItem) {
    if (this.included == null) {
      this.included = new ArrayList<>();
    }
    this.included.add(includedItem);
    return this;
  }

   /**
   * Defines which items are included in a discount.
   * @return included
  **/
  @javax.annotation.Nullable
  public List<ApplicableTo> getIncluded() {
    return included;
  }


  public void setIncluded(List<ApplicableTo> included) {
    this.included = included;
  }


  public ValidationRuleBaseApplicableTo includedAll(Boolean includedAll) {
    
    this.includedAll = includedAll;
    return this;
  }

   /**
   * Indicates whether all items are included in the discount.
   * @return includedAll
  **/
  @javax.annotation.Nullable
  public Boolean getIncludedAll() {
    return includedAll;
  }


  public void setIncludedAll(Boolean includedAll) {
    this.includedAll = includedAll;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidationRuleBaseApplicableTo validationRuleBaseApplicableTo = (ValidationRuleBaseApplicableTo) o;
    return Objects.equals(this.excluded, validationRuleBaseApplicableTo.excluded) &&
        Objects.equals(this.included, validationRuleBaseApplicableTo.included) &&
        Objects.equals(this.includedAll, validationRuleBaseApplicableTo.includedAll);
  }

  @Override
  public int hashCode() {
    return Objects.hash(excluded, included, includedAll);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidationRuleBaseApplicableTo {\n");
    sb.append("    excluded: ").append(toIndentedString(excluded)).append("\n");
    sb.append("    included: ").append(toIndentedString(included)).append("\n");
    sb.append("    includedAll: ").append(toIndentedString(includedAll)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("excluded");
    openapiFields.add("included");
    openapiFields.add("included_all");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ValidationRuleBaseApplicableTo
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ValidationRuleBaseApplicableTo.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ValidationRuleBaseApplicableTo is not found in the empty JSON string", ValidationRuleBaseApplicableTo.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ValidationRuleBaseApplicableTo.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ValidationRuleBaseApplicableTo` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("excluded") != null && !jsonObj.get("excluded").isJsonNull()) {
        JsonArray jsonArrayexcluded = jsonObj.getAsJsonArray("excluded");
        if (jsonArrayexcluded != null) {
          // ensure the json data is an array
          if (!jsonObj.get("excluded").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `excluded` to be an array in the JSON string but got `%s`", jsonObj.get("excluded").toString()));
          }

          // validate the optional field `excluded` (array)
          for (int i = 0; i < jsonArrayexcluded.size(); i++) {
            ApplicableTo.validateJsonElement(jsonArrayexcluded.get(i));
          };
        }
      }
      if (jsonObj.get("included") != null && !jsonObj.get("included").isJsonNull()) {
        JsonArray jsonArrayincluded = jsonObj.getAsJsonArray("included");
        if (jsonArrayincluded != null) {
          // ensure the json data is an array
          if (!jsonObj.get("included").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `included` to be an array in the JSON string but got `%s`", jsonObj.get("included").toString()));
          }

          // validate the optional field `included` (array)
          for (int i = 0; i < jsonArrayincluded.size(); i++) {
            ApplicableTo.validateJsonElement(jsonArrayincluded.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ValidationRuleBaseApplicableTo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ValidationRuleBaseApplicableTo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ValidationRuleBaseApplicableTo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ValidationRuleBaseApplicableTo.class));

       return (TypeAdapter<T>) new TypeAdapter<ValidationRuleBaseApplicableTo>() {
           @Override
           public void write(JsonWriter out, ValidationRuleBaseApplicableTo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ValidationRuleBaseApplicableTo read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ValidationRuleBaseApplicableTo given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ValidationRuleBaseApplicableTo
  * @throws IOException if the JSON string is invalid with respect to ValidationRuleBaseApplicableTo
  */
  public static ValidationRuleBaseApplicableTo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ValidationRuleBaseApplicableTo.class);
  }

 /**
  * Convert an instance of ValidationRuleBaseApplicableTo to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

