/*
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets DiscountAmountVouchersEffectTypes
 */
@JsonAdapter(DiscountAmountVouchersEffectTypes.Adapter.class)
public enum DiscountAmountVouchersEffectTypes {
  
  ORDER("APPLY_TO_ORDER"),
  
  ITEMS("APPLY_TO_ITEMS"),
  
  ITEMS_PROPORTIONALLY("APPLY_TO_ITEMS_PROPORTIONALLY"),
  
  ITEMS_PROPORTIONALLY_BY_QUANTITY("APPLY_TO_ITEMS_PROPORTIONALLY_BY_QUANTITY"),
  
  ITEMS_BY_QUANTITY("APPLY_TO_ITEMS_BY_QUANTITY");

  private String value;

  DiscountAmountVouchersEffectTypes(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static DiscountAmountVouchersEffectTypes fromValue(String value) {
    for (DiscountAmountVouchersEffectTypes b : DiscountAmountVouchersEffectTypes.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<DiscountAmountVouchersEffectTypes> {
    @Override
    public void write(final JsonWriter jsonWriter, final DiscountAmountVouchersEffectTypes enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public DiscountAmountVouchersEffectTypes read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return DiscountAmountVouchersEffectTypes.fromValue(value);
    }
  }
}

