/*
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.DiscountUnitVouchersEffectTypes;
import org.openapitools.client.model.SimpleProductDiscountUnit;
import org.openapitools.client.model.SimpleSkuDiscountUnit;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * DiscountUnit
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-16T13:33:47.147825+01:00[Europe/Warsaw]")
public class DiscountUnit {
  /**
   * Discount type.
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    UNIT("UNIT");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type = TypeEnum.UNIT;

  public static final String SERIALIZED_NAME_UNIT_OFF = "unit_off";
  @SerializedName(SERIALIZED_NAME_UNIT_OFF)
  private Integer unitOff;

  public static final String SERIALIZED_NAME_UNIT_OFF_FORMULA = "unit_off_formula";
  @SerializedName(SERIALIZED_NAME_UNIT_OFF_FORMULA)
  private String unitOffFormula;

  public static final String SERIALIZED_NAME_EFFECT = "effect";
  @SerializedName(SERIALIZED_NAME_EFFECT)
  private DiscountUnitVouchersEffectTypes effect;

  public static final String SERIALIZED_NAME_UNIT_TYPE = "unit_type";
  @SerializedName(SERIALIZED_NAME_UNIT_TYPE)
  private String unitType;

  public static final String SERIALIZED_NAME_PRODUCT = "product";
  @SerializedName(SERIALIZED_NAME_PRODUCT)
  private SimpleProductDiscountUnit product;

  public static final String SERIALIZED_NAME_SKU = "sku";
  @SerializedName(SERIALIZED_NAME_SKU)
  private SimpleSkuDiscountUnit sku;

  public static final String SERIALIZED_NAME_IS_DYNAMIC = "is_dynamic";
  @SerializedName(SERIALIZED_NAME_IS_DYNAMIC)
  private Boolean isDynamic;

  public DiscountUnit() {
  }

  public DiscountUnit type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * Discount type.
   * @return type
  **/
  @javax.annotation.Nonnull
  public TypeEnum getType() {
    return type;
  }


  public void setType(TypeEnum type) {
    this.type = type;
  }


  public DiscountUnit unitOff(Integer unitOff) {
    
    this.unitOff = unitOff;
    return this;
  }

   /**
   * Number of units to be granted a full value discount.
   * @return unitOff
  **/
  @javax.annotation.Nullable
  public Integer getUnitOff() {
    return unitOff;
  }


  public void setUnitOff(Integer unitOff) {
    this.unitOff = unitOff;
  }


  public DiscountUnit unitOffFormula(String unitOffFormula) {
    
    this.unitOffFormula = unitOffFormula;
    return this;
  }

   /**
   * Get unitOffFormula
   * @return unitOffFormula
  **/
  @javax.annotation.Nullable
  public String getUnitOffFormula() {
    return unitOffFormula;
  }


  public void setUnitOffFormula(String unitOffFormula) {
    this.unitOffFormula = unitOffFormula;
  }


  public DiscountUnit effect(DiscountUnitVouchersEffectTypes effect) {
    
    this.effect = effect;
    return this;
  }

   /**
   * Get effect
   * @return effect
  **/
  @javax.annotation.Nullable
  public DiscountUnitVouchersEffectTypes getEffect() {
    return effect;
  }


  public void setEffect(DiscountUnitVouchersEffectTypes effect) {
    this.effect = effect;
  }


  public DiscountUnit unitType(String unitType) {
    
    this.unitType = unitType;
    return this;
  }

   /**
   * The product deemed as free, chosen from product inventory (e.g. time, items).
   * @return unitType
  **/
  @javax.annotation.Nonnull
  public String getUnitType() {
    return unitType;
  }


  public void setUnitType(String unitType) {
    this.unitType = unitType;
  }


  public DiscountUnit product(SimpleProductDiscountUnit product) {
    
    this.product = product;
    return this;
  }

   /**
   * Get product
   * @return product
  **/
  @javax.annotation.Nullable
  public SimpleProductDiscountUnit getProduct() {
    return product;
  }


  public void setProduct(SimpleProductDiscountUnit product) {
    this.product = product;
  }


  public DiscountUnit sku(SimpleSkuDiscountUnit sku) {
    
    this.sku = sku;
    return this;
  }

   /**
   * Get sku
   * @return sku
  **/
  @javax.annotation.Nullable
  public SimpleSkuDiscountUnit getSku() {
    return sku;
  }


  public void setSku(SimpleSkuDiscountUnit sku) {
    this.sku = sku;
  }


  public DiscountUnit isDynamic(Boolean isDynamic) {
    
    this.isDynamic = isDynamic;
    return this;
  }

   /**
   * Flag indicating whether the discount was calculated using a formula.
   * @return isDynamic
  **/
  @javax.annotation.Nullable
  public Boolean getIsDynamic() {
    return isDynamic;
  }


  public void setIsDynamic(Boolean isDynamic) {
    this.isDynamic = isDynamic;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DiscountUnit discountUnit = (DiscountUnit) o;
    return Objects.equals(this.type, discountUnit.type) &&
        Objects.equals(this.unitOff, discountUnit.unitOff) &&
        Objects.equals(this.unitOffFormula, discountUnit.unitOffFormula) &&
        Objects.equals(this.effect, discountUnit.effect) &&
        Objects.equals(this.unitType, discountUnit.unitType) &&
        Objects.equals(this.product, discountUnit.product) &&
        Objects.equals(this.sku, discountUnit.sku) &&
        Objects.equals(this.isDynamic, discountUnit.isDynamic);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, unitOff, unitOffFormula, effect, unitType, product, sku, isDynamic);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DiscountUnit {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    unitOff: ").append(toIndentedString(unitOff)).append("\n");
    sb.append("    unitOffFormula: ").append(toIndentedString(unitOffFormula)).append("\n");
    sb.append("    effect: ").append(toIndentedString(effect)).append("\n");
    sb.append("    unitType: ").append(toIndentedString(unitType)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("    isDynamic: ").append(toIndentedString(isDynamic)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("type");
    openapiFields.add("unit_off");
    openapiFields.add("unit_off_formula");
    openapiFields.add("effect");
    openapiFields.add("unit_type");
    openapiFields.add("product");
    openapiFields.add("sku");
    openapiFields.add("is_dynamic");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("type");
    openapiRequiredFields.add("unit_type");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to DiscountUnit
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DiscountUnit.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DiscountUnit is not found in the empty JSON string", DiscountUnit.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DiscountUnit.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DiscountUnit` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DiscountUnit.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      try {
        JsonElement objectElement = jsonObj.get("type");

        if (objectElement != null && !objectElement.isJsonNull()) {
          TypeEnum.fromValue(objectElement.getAsString());
        } else {
          throw new IllegalArgumentException("Expected the field `type` to be not null");
        }
      } catch (IllegalArgumentException e) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a valid element of TypeEnum enum got `%s` instead", jsonObj.get("type").toString()));
      }
      if ((jsonObj.get("unit_off_formula") != null && !jsonObj.get("unit_off_formula").isJsonNull()) && !jsonObj.get("unit_off_formula").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `unit_off_formula` to be a primitive type in the JSON string but got `%s`", jsonObj.get("unit_off_formula").toString()));
      }
      if (!jsonObj.get("unit_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `unit_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("unit_type").toString()));
      }
      // validate the optional field `product`
      if (jsonObj.get("product") != null && !jsonObj.get("product").isJsonNull()) {
        SimpleProductDiscountUnit.validateJsonElement(jsonObj.get("product"));
      }
      // validate the optional field `sku`
      if (jsonObj.get("sku") != null && !jsonObj.get("sku").isJsonNull()) {
        SimpleSkuDiscountUnit.validateJsonElement(jsonObj.get("sku"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DiscountUnit.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DiscountUnit' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DiscountUnit> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DiscountUnit.class));

       return (TypeAdapter<T>) new TypeAdapter<DiscountUnit>() {
           @Override
           public void write(JsonWriter out, DiscountUnit value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DiscountUnit read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DiscountUnit given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DiscountUnit
  * @throws IOException if the JSON string is invalid with respect to DiscountUnit
  */
  public static DiscountUnit fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DiscountUnit.class);
  }

 /**
  * Convert an instance of DiscountUnit to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

