/*
 * Voucherify API
 * Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.
 *
 * The version of the OpenAPI document: v2018-08-01
 * Contact: support@voucherify.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ExportRedemptionOrder
 */
@JsonAdapter(ExportRedemptionOrder.Adapter.class)
public enum ExportRedemptionOrder {
  
  ID("id"),
  
  _ID("-id"),
  
  OBJECT("object"),
  
  _OBJECT("-object"),
  
  DATE("date"),
  
  _DATE("-date"),
  
  VOUCHER_CODE("voucher_code"),
  
  _VOUCHER_CODE("-voucher_code"),
  
  CAMPAIGN("campaign"),
  
  _CAMPAIGN("-campaign"),
  
  PROMOTION_TIER_ID("promotion_tier_id"),
  
  _PROMOTION_TIER_ID("-promotion_tier_id"),
  
  CUSTOMER_ID("customer_id"),
  
  _CUSTOMER_ID("-customer_id"),
  
  CUSTOMER_SOURCE_ID("customer_source_id"),
  
  _CUSTOMER_SOURCE_ID("-customer_source_id"),
  
  CUSTOMER_NAME("customer_name"),
  
  _CUSTOMER_NAME("-customer_name"),
  
  TRACKING_ID("tracking_id"),
  
  _TRACKING_ID("-tracking_id"),
  
  ORDER_AMOUNT("order_amount"),
  
  _ORDER_AMOUNT("-order_amount"),
  
  GIFT_AMOUNT("gift_amount"),
  
  _GIFT_AMOUNT("-gift_amount"),
  
  LOYALTY_POINTS("loyalty_points"),
  
  _LOYALTY_POINTS("-loyalty_points"),
  
  RESULT("result"),
  
  _RESULT("-result"),
  
  FAILURE_CODE("failure_code"),
  
  _FAILURE_CODE("-failure_code"),
  
  FAILURE_MESSAGE("failure_message"),
  
  _FAILURE_MESSAGE("-failure_message"),
  
  METADATA("metadata"),
  
  _METADATA("-metadata");

  private String value;

  ExportRedemptionOrder(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ExportRedemptionOrder fromValue(String value) {
    for (ExportRedemptionOrder b : ExportRedemptionOrder.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ExportRedemptionOrder> {
    @Override
    public void write(final JsonWriter jsonWriter, final ExportRedemptionOrder enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ExportRedemptionOrder read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ExportRedemptionOrder.fromValue(value);
    }
  }
}

